### ISSUE TITLE
Support for Jupyter lab?

### ISSUE THREAD

**Issue by GaurangTandon** [YoogottamK/jupyter-notebook-solarized-dark#1]
I personally use Jupyter Lab a lot more, and both Lab and Notebook are pretty similar. Is it possible to add some additional css to cover Lab as well?

**Comment by yoogottamk** [comment]
I can but let's consider this:

1. jupyterlab already has a dark theme `[Settings -> JupyterLab Theme -> JupyterLab Dark]`
2. jupyterlab already has a solarized dark theme for the editor `[Settings -> Text Editor Theme -> solarized dark]`

It looks pretty good

**Comment by yoogottamk** [comment]
Turns out that notebooks didn't use solarized dark theme. Also, it took me around 10 extra lines to provide this. So, done! 96f25ecfed598759feb1ad84fa2eab7de05892cd :smile:

If there are any issues with this, please open an issue. I am closing this for now.

Thanks!
