### ISSUE TITLE
Bad contrast ratio for text colors

### ISSUE THREAD

**Issue by GaurangTandon** [YoogottamK/jupyter-notebook-solarized-dark#2]
I know it's not you who came up with the colors, but could you slightly tweak them to provide better contrast?

The problematic declaration:

```
.rendered_html {
    color: var(--base0) !important;
}
```

![image](https://user-images.githubusercontent.com/6308683/58385108-d00b3580-8008-11e9-8c4d-c1f43565ab52.png)

As we can see this contrast ratio can certainly be improved.

**Comment by yoogottamk** [comment]
[This](https://webaim.org/resources/contrastchecker/?fcolor=839496&bcolor=002B36) seems to give a different contrast ratio.

Anyways, I have changed the color 82132c4686d2f313826bbdb51e1763cf552c9451 and now [these](https://webaim.org/resources/contrastchecker/?fcolor=93A1A1&bcolor=002B36) are the ratios.

**Comment by GaurangTandon** [comment]
You can reference issue number (`fixes #2`) in the commit message to avoid having to link to the commit. Thanks btw!
